#######################################################################################################################
#                                                                                                                     #
# FileName    [overlap_exception.py]                                                                                  #
#                                                                                                                     #
# PackageName [overlaps_topics]                                                                                       #
#                                                                                                                     #
# Synopsis    [This file contains the classes for the exceptions used for the result of the algorithm                 #
#              k_clique_comunitiesof networkx. One is a generic exception and the other is the three exceptions       #
#              that can be raised.]                                                                                   #
#                                                                                                                     #
# Author      [Leonardo Picchiami]                                                                                    #
#                                                                                                                     #
#######################################################################################################################



class TopicException(Exception):
    '''
    Generic exception class for topics. Class that directly inherits Exception, 
    will never be raised acting as a superclass to the three main exceptions for the k_clique_communities algorithm.
    '''
    
    def __init__(self, message):
        '''
        Parameters
        ----------
        message : string
            String message containing the explanation of the error that will be printed on the stderr.
        '''
        super(TopicException, self).__init__(message)


        
class TopicMalFormedException(TopicException):
    '''
    Exception class indicating that a topic is not well formed.
    It does not contain any representative keywords of the generated k topics.
    '''
    
    def __init__(self, message):
        '''
        Parameters
        ----------
        message : string
            String message containing the explanation of the error that will be printed on the stderr.
        '''
        
        super(TopicMalFormedException, self).__init__(message)


        
class TopicNotAllKeywordsUsedException(TopicException):
    '''
    Exception class indicating that at least one of the keywords recovered is not part of any topic.
    '''
    
    def __init__(self, message):
        '''
        Parameters
        ----------
        message : string
            String message containing the explanation of the error that will be printed on the stderr.
        '''
        
        super(TopicNotAllKeywordsUsedException, self).__init__(message)


        
class TopicTooManyException(TopicException):
    '''
    Exception class indicating whether the number of topics generated by the clique percolation (k_clique_communities algorithm) method
    is greater than k.
    '''
    
    def __init__(self, message):
        '''
        Parameters
        ----------
        message : string
            String message containing the explanation of the error that will be printed on the stderr.
        '''
        
        super(TopicTooManyException, self).__init__(message)
    
